// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtcxtvuxatocugnucmgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0Y3h0dnV4YXRvY3VnbnVjbWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzgxOTgsImV4cCI6MjA2MjExNDE5OH0.QiPk3sCTsn2waR07cxCW8TDSaSGr_Pnz8BtX1PiwzU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);